### ISSUE TITLE
[Refactor] AddProduct페이지 최적화

### ISSUE THREAD

**Issue by wjddnjswjd12** [Team-IT-DA/Frontend#101]
## 📌 개요
add Product 페이지 최적화 
input창에 입력 할 때마다 생기는 리렌더링 해결하기.

## 👩‍💻 작업 사항

- [x] Header 분리
- [x] input 여러개로 나눠보기

### ✅ 참고 사항

여러 시도를 해봤습니다.
일단 첫번째로, TextArea를 따로  빼봤습니다
그리고 Input 14개를 각각 다른 recoil로 나누어봤습니다.

지금 관리할 상태가 14개인데, `map`을 당연히 돌려야하는 상황입니다.
같은 Component인 TextField를 공유하는 input들에 변화가 생기니까
어쩔수없이 14개 다 리렌더링이 발생합니다.

그렇다면 굳이 리렌더링을 방지하기 위해 서로 다른 Input 컴포넌트를 14개로 분리해야 하는 상황인데
그렇다면 코드가 이런식으로 되겠죠
```
<ProductNameInput />
<ProductDescriptionInput />
<ProductPriceInput />
<ProductSalesInput />
<Product어쩌구1Input />
<Product어쩌구2Input />
<Product어쩌구3Input />
<Product어쩌구4Input />
<Product어쩌구5Input />
<Product어쩌구6Input />
<Product어쩌구7Input />
<Product어쩌구8Input />
```
그리고 onchange 핸들러도 각자 만들어줘야해요

나눌수 있을까? 라는 생각에 이상한 switch case문도 만들어보려했는데
![image](https://user-images.githubusercontent.com/71004200/131207311-50f9e282-d781-4f0a-968a-e46d668d7404.png)
useRecoilState는 컴포넌트 내에서만 부를수있다면서 오류가 떠서 이런 방식도 안될것같네요

**Comment by damilog** [comment]
여러가지 시도를 하셨네요. onChange 핸들러를 각각 만들어 줘야하는 부분도 그렇고 상태를 나눠도 어차피 다같이 리렌더링 되는 구조라 상태분리가 의미 없었군요ㅠㅠ 고생하셨습니다ㅎㅎ 
해당 페이지는 판매자가 어느정도 시간을 들여서 작성하는 페이지인 만큼 onChange 이벤트 발생할 때마다 리렌더링 되는 횟수를 최소화 하는 방법으로 디바운스(1.5초..단위로 저장..?  넘 느린가)가 떠오르긴하는데, 여러 예외사항들, 예를 들어 이미 작성된 상품 페이지를 수정할 때 유저가 디바운스 지연시간 (1.5)초보다 빨리 수정하고 나가버리는 경우.. 등을 처리할 수있을지 아직 확신이 안 드네요ㅋㅋㅋ 일단 참고만 해주세요!!

**Comment by wjddnjswjd12** [comment]
> 여러가지 시도를 하셨네요. onChange 핸들러를 각각 만들어 줘야하는 부분도 그렇고 상태를 나눠도 어차피 다같이 리렌더링 되는 구조라 상태분리가 의미 없었군요ㅠㅠ 고생하셨습니다ㅎㅎ
> 해당 페이지는 판매자가 어느정도 시간을 들여서 작성하는 페이지인 만큼 onChange 이벤트 발생할 때마다 리렌더링 되는 횟수를 최소화 하는 방법으로 디바운스(1.5초..단위로 저장..? 넘 느린가)가 떠오르긴하는데, 여러 예외사항들, 예를 들어 이미 작성된 상품 페이지를 수정할 때 유저가 디바운스 지연시간 (1.5)초보다 빨리 수정하고 나가버리는 경우.. 등을 처리할 수있을지 아직 확신이 안 드네요ㅋㅋㅋ 일단 참고만 해주세요!!

오 근데 디바운스 진짜 좋을것같아요 막 뇌에서ㅓ는 될것도같은데? 싶은데... 한번 시도는 해보겠습니다!!! 타자가 빠르다는 가정 하에 1초..?ㅎㅎ 데이지 최적화하신거 보고 저도 삘받아서 이번에 한번 좀 깊게 해봤는데 좋은 경험이였던것같아요! 다른 방법들ㅇ ㅣㅆ으면 더 도전해봐야겠습니다~
