### ISSUE TITLE
Card쪽 font-size 조절

### ISSUE THREAD

**Issue by wjddnjswjd12** [Team-IT-DA/Frontend#14]
drawer 구현 중 small card의 font-size가 너무 큰 느낌을 받음
- small, large에 따른 font-size 조절

**Comment by wjddnjswjd12** [comment]
추가로 팀원과 고민하면 좋을 점:
- 2줄이상 넘어가고, 길이가 제목 길이가 너무 길면 {...} 점점점 표시가 뜨도록 설정했음
- webkit을 사용하지 않으면 2줄 이상을 설정 할 방법이 없음 (무조건 한 줄만 ... 처리 할 수 있음)
- 일단 두줄정도는 확보하고 나머지 넘치는 제목길이를 ... 처리 해야 할 것 같아서 webkit을 적용
- 하지만 그놈의 IE에서는 ... 처리가 안됨.
- IE를 벌고 갈까...라는 생각이 80프로 ㅎㅎ;^^

참고로 ... 처리는 아래의 경우를 말함:
![image](https://user-images.githubusercontent.com/71004200/127440349-56f92c34-619a-4e9f-8521-fb7560731735.png)

**Comment by wjddnjswjd12** [comment]
++ border속성을 그냥 카드에서는 줘도 이쁜 것 같은데, sideDrawer에서 주니까 좀 별로인 것 같음
이것도 추후 상의 해봐야 함

**Comment by ha3158987** [comment]
> 추가로 팀원과 고민하면 좋을 점:
> 
> * 2줄이상 넘어가고, 길이가 제목 길이가 너무 길면 {...} 점점점 표시가 뜨도록 설정했음
> * webkit을 사용하지 않으면 2줄 이상을 설정 할 방법이 없음 (무조건 한 줄만 ... 처리 할 수 있음)
> * 일단 두줄정도는 확보하고 나머지 넘치는 제목길이를 ... 처리 해야 할 것 같아서 webkit을 적용
> * 하지만 그놈의 IE에서는 ... 처리가 안됨.
> * IE를 버리고 갈까...라는 생각이 80프로 ㅎㅎ;^^
> 
> 참고로 ... 처리는 아래의 경우를 말함:
> ![image](https://user-images.githubusercontent.com/71004200/127440349-56f92c34-619a-4e9f-8521-fb7560731735.png)

IE얘기가 나와서 생각이 난건데 IE에서는 flexbox가 지원이 안된다고 해서 같이 얘기해봐야겠다 생각했어요!
header만 해도 flex가 굉장히 많이 쓰이고 있는 터라... IE를 버린다면 상관이 없을 것 같은데 흠🤔
![image](https://user-images.githubusercontent.com/65105537/127576107-197a1c1e-7a45-4b11-b881-5a0766ca5b07.png)
