### ISSUE TITLE
[FEAT] Product Detail 페이지 API 붙이기

### ISSUE THREAD

**Issue by wjddnjswjd12** [Team-IT-DA/Frontend#174]
## 📌 개요

Product Detail 페이지 API 붙이기

## 👩‍💻 작업 사항

- [x] Product Detail 페이지 API 붙이기
- [x] addProduct에 Category불러오는 부분도 마무리 해두기
- [x] Category 고르는 Select Box 하나 만들기

### ✅ 참고 사항

공유할 내용, 스크린샷 등을 넣어 주세요.

## 데이지랑 겹치거나 충돌날것 같은 부분
카테고리 리스트 불러오는게 상품 추가 페이지에서도 필요하기에 일단 `productAPI.js`에 저렇게 불러왔는데... 데이지도 작업하시다가 불러오실 것 같아서 나중에 한번 맞춰봅시당
![image](https://user-images.githubusercontent.com/71004200/135723127-d780290b-bb38-4e26-a738-8a1cac399d12.png)

## interceptor변경사항
response.data를 모든곳에 적용해두었습니당.
이유는 모르겠지만 `response.data.data`까지 하고싶은데, AxiosResponse관련 typescript문제로 어쩔수없이 `response.data`만 해두었습니다 ㅠ
![image](https://user-images.githubusercontent.com/71004200/135723153-1eadba35-ac0c-4bff-a289-07d5f8b21914.png)

**- `response.data.data`까지 하고싶은 이유:**

### 끔찍..😫

![image](https://user-images.githubusercontent.com/71004200/135723236-5b5fe170-c8ec-46ed-873b-4e4b104cadae.png)

**Comment by damilog** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋdata?.data?.product?. ㅋㅋㅋ 웃고갑니다
