### ISSUE TITLE
Home Page 설계 및 구현

### ISSUE THREAD

**Issue by damilog** [Team-IT-DA/Frontend#5]
## 📌 개요

홈페이지 뷰 만들기
브랜드스토리 페이지 뷰 만들기 

## 👩‍💻 작업 사항

- [x] 홈페이지 배경이미지 정상 렌더링 되게 수정
- 

### ✅  참고 스크린 샷

참고 스크린샷을 넣어 주세요.

* 추가적인 공유가 필요한 사항은 Comment

**Comment by ha3158987** [comment]
Resolved with PR #33
