### ISSUE TITLE
[FIX] Home 스타일 수정

### ISSUE THREAD

**Issue by damilog** [Team-IT-DA/Frontend#69]
## 📌 개요
- 오늘 develop 브랜치 pull 후 맥북 13인치 모니터에서 100% 비율로 확인해봤는데 이렇게 나와서 공유차 이슈 만들었습니다🙂
- 나중에 시간 되실 때 작업 부탁드려요!!
## 👩‍💻 작업 사항

- MainPage 스타일 수정

### ✅  참고 스크린 샷

![image](https://user-images.githubusercontent.com/56783350/129162126-b4f68858-374f-4691-8af4-73618ff37690.png)

**Comment by ha3158987** [comment]
헉...!!🤭  확인했습니다~! 스타일 수정해서 반영해둘게요 :)
